In [11]:
import pandas as pd
import openpyxl
import sys
sys.path.append('../')
from src import sp_eda as se
pd.set_option('display.max_columns', None)

### Insertamos los datos del csv

In [12]:
df1=pd.read_csv('../data/bank-additional.csv')

In [13]:
se.eda_prelim(df1)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
26495,26617,29.0,blue-collar,SINGLE,basic.9y,0.0,1.0,0.0,cellular,249,1,999,0,NONEXISTENT,-0.1,"93,2",-42,"4,076","5195,8",no,9-junio-2018,33.515,-76.151,885a7225-b2fb-4212-a4d8-867bc4faebf0
30025,30169,40.0,admin.,MARRIED,high.school,0.0,1.0,0.0,cellular,401,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,365","5099,1",no,29-abril-2018,27.067,-91.602,00815df3-2a7a-4030-80c4-996a3008a859
8888,8985,43.0,admin.,MARRIED,NaN,0.0,1.0,0.0,telephone,189,2,999,0,NONEXISTENT,1.4,"94,465","-41,8","4,866","5228,1",no,13-agosto-2016,45.029,-93.902,c3d39a28-cba4-488f-a422-7ff79f07931a
31908,32052,30.0,blue-collar,MARRIED,basic.4y,0.0,0.0,0.0,cellular,208,1,999,1,FAILURE,-1.8,"92,893","-46,2","1,327","5099,1",no,18-noviembre-2017,47.953,-108.418,7740875a-6509-4798-92a6-f7cb27c15d61
33986,34130,NaN,technician,MARRIED,professional.course,0.0,0.0,0.0,cellular,65,2,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,281","5099,1",no,26-mayo-2018,47.911,-76.875,ece511b5-47b9-422f-8b81-be58da6a886d

----------
DIMENSIONES
El conjunto de datos presenta 43000 filas y 24 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  object
 3   marital         42915 non-null  object
 4   education       41193 non-null  object
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  object
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  object
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  object
 16  cons.conf.idx   43000 non-null  object
 17  euribor3m       33744 non-null  object
 18  nr.employed     43000 non-null  object
 19  y               43000 non-null  object
 20  date            42752 non-null  object
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  object
dtypes: float64(7), int64(5), object(12)
memory usage: 7.9+ MB

None

----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS

Unnamed: 0         0.000000
age               11.906977
job                0.802326
marital            0.197674
education          4.202326
default           20.886047
housing            2.386047
loan               2.386047
contact            0.000000
duration           0.000000
campaign           0.000000
pdays              0.000000
previous           0.000000
poutcome           0.000000
emp.var.rate       0.000000
cons.price.idx     1.095349
cons.conf.idx      0.000000
euribor3m         21.525581
nr.employed        0.000000
y                  0.000000
date               0.576744
latitude           0.000000
longitude          0.000000
id_                0.000000
dtype: float64

----------
FRECUENCIA CATEGORÍAS
job
admin.           10873
blue-collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self-employed     1489
housemaid         1123
unemployed        1063
student            903
NaN                345
Name: count, dtype: int64
-----------
marital
MARRIED     25999
SINGLE      12105
DIVORCED     4811
NaN            85
Name: count, dtype: int64
-----------
education
university.degree      12722
high.school             9925
basic.9y                6309
professional.course     5477
basic.4y                4356
basic.6y                2386
NaN                     1807
illiterate                18
Name: count, dtype: int64
-----------
contact
cellular     27396
telephone    15604
Name: count, dtype: int64
-----------
poutcome
NONEXISTENT    37103
FAILURE         4461
SUCCESS         1436
Name: count, dtype: int64
-----------
cons.price.idx
93,994    7938
93,918    6937
92,893    5985
93,444    5349
94,465    4522
93,2      3731
93,075    2552
92,201     803
92,963     742
NaN        471
92,431     471
92,649     375
94,215     320
94,199     316
92,843     298
92,379     274
93,369     271
94,027     242
94,055     236
93,876     224
94,601     212
92,469     184
92,713     179
93,749     179
94,767     130
93,798      48
92,756      11
Name: count, dtype: int64
-----------
cons.conf.idx
-36,4    8020
-42,7    7004
-46,2    6057
-36,1    5408
-41,8    4568
-42      3782
-47,1    2581
-31,4     815
-40,8     748
-26,9     477
-30,1     379
-40,3     328
-37,5     318
-50       299
-29,8     277
-34,8     275
-38,3     245
-39,8     239
-40       225
-49,5     214
-33,6     185
-34,6     183
-33       181
-50,8     133
-40,4      48
-45,9      11
Name: count, dtype: int64
-----------
euribor3m
NaN      9256
4,857    2287
4,962    2124
4,963    2019
4,961    1594
         ...
3,743       1
3,563       1
3,488       1
3,428       1
0,969       1
Name: count, Length: 310, dtype: int64
-----------
nr.employed
5228,1    16980
5099,1     8937
5191       8020
5195,8     3830
5076,2     1748
5017,5     1133
4991,6      812
5008,7      683
4963,6      665
5023,5      181
5176,3       11
Name: count, dtype: int64
-----------
y
no     38156
yes     4844
Name: count, dtype: int64
-----------
date
NaN                  248
28-febrero-2018       95
28-febrero-2016       94
28-febrero-2015       92
28-febrero-2017       89
                    ...
2-julio-2016          11
14-abril-2015         10
20-noviembre-2015     10
4-abril-2017          10
21-diciembre-2019     10
Name: count, Length: 1826, dtype: int64
-----------
id_
089b39d8-e4d0-461b-87d4-814d71e0e079    1
c25b5d31-bb7e-41af-898d-42bf3e479351    1
bfd6bad9-f23a-445a-838e-10ee90110534    1
075b0e72-b5e3-43f4-90cd-29f9090b2b1a    1
482a2d86-c9f0-46b7-9f6f-82c769690d48    1
                                       ..
27e317a2-722c-454d-850b-97b536029c81    1
6d9c117f-af67-4a89-83db-caf514a42374    1
6a229b87-6bf9-4339-9639-b98555df71e7    1
cc891cf7-206c-47f0-804f-20b5b757d5fc    1
993bbbd6-4dbc-4a40-a408-f91f8462bee6    1
Name: count, Length: 43000, dtype: int64
-----------

### Insertamos los datos del xlxs, incorporando las distintas hojas en el mismo dataframe

In [14]:
hojas=pd.read_excel('../data/customer-details.xlsx',sheet_name=None)

In [15]:
df_details_completo= pd.concat(hojas.values(),ignore_index=True)

In [16]:
se.eda_prelim(df_details_completo)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
9326,9326,35041,1,2,2012-12-10,6,66e4641f-8ad4-4601-b879-2c16da1db312
24097,3982,33725,0,2,2013-04-09,5,4625e235-895e-45c7-bed2-3670d1ed2d94
28534,8419,90058,0,1,2013-10-16,12,8a051e98-d04a-485d-bea6-46447f760481
30928,1848,34650,0,0,2014-01-19,27,f4571a6f-534f-4d11-b2db-274fe40732c8
2008,2008,108442,0,2,2012-01-05,1,012d25b6-9eff-4b4b-ba43-327421507f39

----------
DIMENSIONES
El conjunto de datos presenta 43170 filas y 7 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 2.3+ MB

None

----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS

Unnamed: 0           0.0
Income               0.0
Kidhome              0.0
Teenhome             0.0
Dt_Customer          0.0
NumWebVisitsMonth    0.0
ID                   0.0
dtype: float64

----------
FRECUENCIA CATEGORÍAS
ID
089b39d8-e4d0-461b-87d4-814d71e0e079    1
38708e69-8996-4d51-956a-d422fd78872d    1
7218c062-4571-4fd9-8bad-c6a09ad1eb5d    1
853e4074-829e-47e4-9287-06b4cb0f814f    1
a185385b-b614-423b-9932-a132ed02eed1    1
                                       ..
8e1e500d-de2a-4e14-b027-20983ebaeeb9    1
bdee816d-7f9d-442a-99e1-cf259021f8f5    1
8d3ae2ee-5363-4508-ac65-cbecc78a08bb    1
4601e86a-18c4-473c-8467-fb16e838be7d    1
9727bc06-c11a-461a-a5bb-3d210467cc2a    1
Name: count, Length: 43170, dtype: int64
-----------

###  Unimos los dos dataframe 
Los vamos a unir a traves de la columna id_. Para ello nos damos cuenta que en df_details_completo la columna ID representa el identificador del cliente al igual que en la columna id_ del df1. Cambiamos el nombre para que coincida y podamos unir los dos dataframes por esa misma columna.Eliminamos las columnas Unnamed porvenientes de los dos df originales.

In [17]:
df_details_completo.rename(columns={'ID':'id_'}, inplace= True)

df=pd.merge(df1,df_details_completo,'outer', 'id_')
df=df.drop(columns=['Unnamed: 0_x','Unnamed: 0_y'])

In [18]:
se.eda_prelim(df)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
22393,50.0,entrepreneur,MARRIED,high.school,0.0,1.0,0.0,cellular,257.0,1.0,999.0,0.0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,4-enero-2015,46.676,-99.626,8442aae4-9490-4424-b315-4abf5b316756,117699,0,1,2014-09-17,25
26943,56.0,services,MARRIED,high.school,NaN,1.0,0.0,telephone,279.0,11.0,999.0,0.0,NONEXISTENT,1.4,"93,918","-42,7","4,962","5228,1",no,11-abril-2018,33.531,-70.446,9f8dddec-3193-4daf-b4b4-60962f0690f4,121389,0,2,2012-06-21,26
11654,32.0,technician,MARRIED,professional.course,0.0,0.0,0.0,telephone,147.0,1.0,999.0,0.0,NONEXISTENT,1.1,"93,994","-36,4","4,858",5191,no,18-septiembre-2015,26.372,-122.962,44d05a7d-7faf-4ed1-a77e-49951610372b,78628,2,1,2012-11-08,16
23397,42.0,blue-collar,MARRIED,basic.4y,0.0,0.0,0.0,cellular,139.0,1.0,999.0,0.0,NONEXISTENT,-1.8,"92,893","-46,2","1,299","5099,1",no,6-junio-2016,45.695,-72.341,8a78afa2-9f91-482e-97c2-01ec8a9025df,62421,1,2,2014-07-11,9
41316,24.0,student,SINGLE,high.school,0.0,0.0,0.0,cellular,115.0,1.0,999.0,1.0,FAILURE,-2.9,"92,469","-33,6","1,029","5076,2",no,24-noviembre-2018,48.903,-81.461,f4dabb65-3f6f-4997-8af1-47d62aa4d191,142577,0,1,2014-05-31,9

----------
DIMENSIONES
El conjunto de datos presenta 43170 filas y 28 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                37880 non-null  float64
 1   job                42655 non-null  object
 2   marital            42915 non-null  object
 3   education          41193 non-null  object
 4   default            34019 non-null  float64
 5   housing            41974 non-null  float64
 6   loan               41974 non-null  float64
 7   contact            43000 non-null  object
 8   duration           43000 non-null  float64
 9   campaign           43000 non-null  float64
 10  pdays              43000 non-null  float64
 11  previous           43000 non-null  float64
 12  poutcome           43000 non-null  object
 13  emp.var.rate       43000 non-null  float64
 14  cons.price.idx     42529 non-null  object
 15  cons.conf.idx      43000 non-null  object
 16  euribor3m          33744 non-null  object
 17  nr.employed        43000 non-null  object
 18  y                  43000 non-null  object
 19  date               42752 non-null  object
 20  latitude           43000 non-null  float64
 21  longitude          43000 non-null  float64
 22  id_                43170 non-null  object
 23  Income             43170 non-null  int64
 24  Kidhome            43170 non-null  int64
 25  Teenhome           43170 non-null  int64
 26  Dt_Customer        43170 non-null  datetime64[ns]
 27  NumWebVisitsMonth  43170 non-null  int64
dtypes: datetime64[ns](1), float64(11), int64(4), object(12)
memory usage: 9.2+ MB

None

----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS

age                  12.253880
job                   1.192958
marital               0.590688
education             4.579569
default              21.197591
housing               2.770442
loan                  2.770442
contact               0.393792
duration              0.393792
campaign              0.393792
pdays                 0.393792
previous              0.393792
poutcome              0.393792
emp.var.rate          0.393792
cons.price.idx        1.484827
cons.conf.idx         0.393792
euribor3m            21.834607
nr.employed           0.393792
y                     0.393792
date                  0.968265
latitude              0.393792
longitude             0.393792
id_                   0.000000
Income                0.000000
Kidhome               0.000000
Teenhome              0.000000
Dt_Customer           0.000000
NumWebVisitsMonth     0.000000
dtype: float64

----------
FRECUENCIA CATEGORÍAS
job
admin.           10873
blue-collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self-employed     1489
housemaid         1123
unemployed        1063
student            903
NaN                515
Name: count, dtype: int64
-----------
marital
MARRIED     25999
SINGLE      12105
DIVORCED     4811
NaN           255
Name: count, dtype: int64
-----------
education
university.degree      12722
high.school             9925
basic.9y                6309
professional.course     5477
basic.4y                4356
basic.6y                2386
NaN                     1977
illiterate                18
Name: count, dtype: int64
-----------
contact
cellular     27396
telephone    15604
NaN            170
Name: count, dtype: int64
-----------
poutcome
NONEXISTENT    37103
FAILURE         4461
SUCCESS         1436
NaN              170
Name: count, dtype: int64
-----------
cons.price.idx
93,994    7938
93,918    6937
92,893    5985
93,444    5349
94,465    4522
93,2      3731
93,075    2552
92,201     803
92,963     742
NaN        641
92,431     471
92,649     375
94,215     320
94,199     316
92,843     298
92,379     274
93,369     271
94,027     242
94,055     236
93,876     224
94,601     212
92,469     184
92,713     179
93,749     179
94,767     130
93,798      48
92,756      11
Name: count, dtype: int64
-----------
cons.conf.idx
-36,4    8020
-42,7    7004
-46,2    6057
-36,1    5408
-41,8    4568
-42      3782
-47,1    2581
-31,4     815
-40,8     748
-26,9     477
-30,1     379
-40,3     328
-37,5     318
-50       299
-29,8     277
-34,8     275
-38,3     245
-39,8     239
-40       225
-49,5     214
-33,6     185
-34,6     183
-33       181
NaN       170
-50,8     133
-40,4      48
-45,9      11
Name: count, dtype: int64
-----------
euribor3m
NaN      9426
4,857    2287
4,962    2124
4,963    2019
4,961    1594
         ...
0,894       1
5,045       1
3,901       1
3,428       1
0,996       1
Name: count, Length: 310, dtype: int64
-----------
nr.employed
5228,1    16980
5099,1     8937
5191       8020
5195,8     3830
5076,2     1748
5017,5     1133
4991,6      812
5008,7      683
4963,6      665
5023,5      181
NaN         170
5176,3       11
Name: count, dtype: int64
-----------
y
no     38156
yes     4844
NaN      170
Name: count, dtype: int64
-----------
date
NaN                  418
28-febrero-2018       95
28-febrero-2016       94
28-febrero-2015       92
28-febrero-2017       89
                    ...
10-diciembre-2019     11
4-abril-2017          10
14-abril-2015         10
20-noviembre-2015     10
21-diciembre-2019     10
Name: count, Length: 1826, dtype: int64
-----------
id_
0000e811-006e-4404-b535-89bf6cd96553    1
aae0e160-fa3f-4600-bcc5-eaa04282351f    1
aacae69b-1b32-4bf6-aa02-3418deec65a7    1
aacef7f3-95b0-4757-9cc0-6b245e621098    1
aad83b20-f30d-4b8f-93cb-3b3d8e2a4929    1
                                       ..
55638993-ae88-4798-ace4-02627c4cd1c9    1
55641010-caf8-4f27-b7cc-56227dbd5ab5    1
5566a218-272e-4636-8124-531df1a07814    1
556731b6-7f49-4504-b484-6c486478bfd0    1
fffe84df-4e63-4465-82de-0d9821d919bf    1
Name: count, Length: 43170, dtype: int64
-----------

Se observan porcentajes de nulos con el mismo valor en muchas columnas. Se cae en la cuenta de que hemos juntado archivos con distinto numero de registos 43000 vs 43170. los 170 de diferencia sobre 43170 representan el 0,39% mostrado en los elementos nulos. Si esos 170 registros de diferencia no tienen datos de comunicación en la campaña, quizas no tenga sentido incluirlos en el análisis. Se propone una unión de dataframes inner o left

In [19]:
df=pd.merge(df1,df_details_completo,'inner', 'id_')
df=df.drop(columns=['Unnamed: 0_x','Unnamed: 0_y'])
se.eda_prelim(df)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
34974,44.0,entrepreneur,SINGLE,university.degree,0.0,1.0,0.0,cellular,210,2,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,25","5099,1",no,25-septiembre-2015,25.214,-79.439,c9846ec2-3262-4dd6-b342-4175fc48d600,124253,0,0,2014-04-08,14
21347,35.0,admin.,MARRIED,university.degree,0.0,1.0,0.0,cellular,344,2,999,0,NONEXISTENT,1.4,"93,444","-36,1","4,963","5228,1",no,15-septiembre-2016,26.828,-69.665,a2e5c3f0-dfe8-4ce8-8b5a-f9a380d3cc17,105142,0,1,2013-11-01,23
17633,54.0,management,MARRIED,university.degree,0.0,0.0,1.0,cellular,218,1,999,0,NONEXISTENT,1.4,"93,918","-42,7",NaN,"5228,1",no,15-junio-2018,25.021,-101.410,9c07df1f-e152-43a8-a036-fef3ba0ee400,46475,1,2,2012-10-10,9
3220,24.0,student,SINGLE,high.school,0.0,0.0,0.0,telephone,597,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,86",5191,no,15-junio-2015,47.228,-68.992,31aa3332-6542-4361-b605-5ae9bd6bea99,18644,1,1,2012-02-28,30
33868,49.0,management,SINGLE,professional.course,0.0,0.0,0.0,cellular,248,1,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,281","5099,1",no,13-agosto-2019,48.637,-116.227,7c657cc0-49eb-4348-8655-c6517f5aa71e,8645,0,2,2014-04-27,2

----------
DIMENSIONES
El conjunto de datos presenta 43000 filas y 28 columnas
----------
INFORMACION DE COLUMNAS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                37880 non-null  float64
 1   job                42655 non-null  object
 2   marital            42915 non-null  object
 3   education          41193 non-null  object
 4   default            34019 non-null  float64
 5   housing            41974 non-null  float64
 6   loan               41974 non-null  float64
 7   contact            43000 non-null  object
 8   duration           43000 non-null  int64
 9   campaign           43000 non-null  int64
 10  pdays              43000 non-null  int64
 11  previous           43000 non-null  int64
 12  poutcome           43000 non-null  object
 13  emp.var.rate       43000 non-null  float64
 14  cons.price.idx     42529 non-null  object
 15  cons.conf.idx      43000 non-null  object
 16  euribor3m          33744 non-null  object
 17  nr.employed        43000 non-null  object
 18  y                  43000 non-null  object
 19  date               42752 non-null  object
 20  latitude           43000 non-null  float64
 21  longitude          43000 non-null  float64
 22  id_                43000 non-null  object
 23  Income             43000 non-null  int64
 24  Kidhome            43000 non-null  int64
 25  Teenhome           43000 non-null  int64
 26  Dt_Customer        43000 non-null  datetime64[ns]
 27  NumWebVisitsMonth  43000 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(8), object(12)
memory usage: 9.2+ MB

None

----------
DUPLICADOS
Tenemos 0 duplicados
----------
ELEMENTOS NULOS

age                  11.906977
job                   0.802326
marital               0.197674
education             4.202326
default              20.886047
housing               2.386047
loan                  2.386047
contact               0.000000
duration              0.000000
campaign              0.000000
pdays                 0.000000
previous              0.000000
poutcome              0.000000
emp.var.rate          0.000000
cons.price.idx        1.095349
cons.conf.idx         0.000000
euribor3m            21.525581
nr.employed           0.000000
y                     0.000000
date                  0.576744
latitude              0.000000
longitude             0.000000
id_                   0.000000
Income                0.000000
Kidhome               0.000000
Teenhome              0.000000
Dt_Customer           0.000000
NumWebVisitsMonth     0.000000
dtype: float64

----------
FRECUENCIA CATEGORÍAS
job
admin.           10873
blue-collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self-employed     1489
housemaid         1123
unemployed        1063
student            903
NaN                345
Name: count, dtype: int64
-----------
marital
MARRIED     25999
SINGLE      12105
DIVORCED     4811
NaN            85
Name: count, dtype: int64
-----------
education
university.degree      12722
high.school             9925
basic.9y                6309
professional.course     5477
basic.4y                4356
basic.6y                2386
NaN                     1807
illiterate                18
Name: count, dtype: int64
-----------
contact
cellular     27396
telephone    15604
Name: count, dtype: int64
-----------
poutcome
NONEXISTENT    37103
FAILURE         4461
SUCCESS         1436
Name: count, dtype: int64
-----------
cons.price.idx
93,994    7938
93,918    6937
92,893    5985
93,444    5349
94,465    4522
93,2      3731
93,075    2552
92,201     803
92,963     742
NaN        471
92,431     471
92,649     375
94,215     320
94,199     316
92,843     298
92,379     274
93,369     271
94,027     242
94,055     236
93,876     224
94,601     212
92,469     184
92,713     179
93,749     179
94,767     130
93,798      48
92,756      11
Name: count, dtype: int64
-----------
cons.conf.idx
-36,4    8020
-42,7    7004
-46,2    6057
-36,1    5408
-41,8    4568
-42      3782
-47,1    2581
-31,4     815
-40,8     748
-26,9     477
-30,1     379
-40,3     328
-37,5     318
-50       299
-29,8     277
-34,8     275
-38,3     245
-39,8     239
-40       225
-49,5     214
-33,6     185
-34,6     183
-33       181
-50,8     133
-40,4      48
-45,9      11
Name: count, dtype: int64
-----------
euribor3m
NaN      9256
4,857    2287
4,962    2124
4,963    2019
4,961    1594
         ...
3,743       1
3,563       1
3,488       1
3,428       1
0,969       1
Name: count, Length: 310, dtype: int64
-----------
nr.employed
5228,1    16980
5099,1     8937
5191       8020
5195,8     3830
5076,2     1748
5017,5     1133
4991,6      812
5008,7      683
4963,6      665
5023,5      181
5176,3       11
Name: count, dtype: int64
-----------
y
no     38156
yes     4844
Name: count, dtype: int64
-----------
date
NaN                  248
28-febrero-2018       95
28-febrero-2016       94
28-febrero-2015       92
28-febrero-2017       89
                    ...
2-julio-2016          11
14-abril-2015         10
20-noviembre-2015     10
4-abril-2017          10
21-diciembre-2019     10
Name: count, Length: 1826, dtype: int64
-----------
id_
089b39d8-e4d0-461b-87d4-814d71e0e079    1
c25b5d31-bb7e-41af-898d-42bf3e479351    1
bfd6bad9-f23a-445a-838e-10ee90110534    1
075b0e72-b5e3-43f4-90cd-29f9090b2b1a    1
482a2d86-c9f0-46b7-9f6f-82c769690d48    1
                                       ..
27e317a2-722c-454d-850b-97b536029c81    1
6d9c117f-af67-4a89-83db-caf514a42374    1
6a229b87-6bf9-4339-9639-b98555df71e7    1
cc891cf7-206c-47f0-804f-20b5b757d5fc    1
993bbbd6-4dbc-4a40-a408-f91f8462bee6    1
Name: count, Length: 43000, dtype: int64
-----------

Guardamos nuestro nuevo archivo con ambos archivos juntos y pasamos a la limpieza

In [20]:
df.to_csv('../data/b_additional_details.csv', index=False)