## Cosas a limpiar  
#### archivo bank-additional.csv
 
●   **age**: cambiar dato a tipo integer    
●	**job**:  la categoría  "admin." es la única que aparece abreviado, cambiar nombre a "administrative"    
●	**marital**: Catergorías en mayúsculas-> cambiar a minusculas  
●	**default**: estudiar el cambio a boolean, o Yes/No, ahora mismo es float   
●	**housing**: estudiar el cambio a boolean, o Yes/No, ahora mismo es float   
●	**loan**: estudiar el cambio a boolean, o Yes/No, ahora mismo es float    
●	**cons.price.idx**: cambiar a float. Cambiar puntos por guiones en el nombre de la columna  
●	**cons.conf.idx**: cambiar a float. Cambiar puntos por guiones en nombre de la columna    
●	**euribor3m**: cambiar a float   

●	**y**: estudiar cambioa  boolean    
●	**date**: cambio de a tipo fecha   
●	**contact_month**: conjunto de datos presenta columna latitude (no tiene sentido).Extraeremos estos datos de la columna 'date'    
●	**contact_year**: conjunto de datos presenta columna longitude (no tiene sentido). Extraeremos los datos de la columna 'date'     

#### Archivo customer-details.xlxs
El archivo parece tener datos consitentes

In [1]:
import pandas as pd
import openpyxl
import locale
import sys
sys.path.append('../')
pd.set_option('display.max_columns', None)

In [2]:
df_raw=pd.read_csv('../data/b_additional_details.csv')

df=df_raw.copy()
df.head(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20

## Cambiar nombre a columnas

In [3]:
df.columns= df.columns.str.replace('.','_').str.lower()
df.columns=df.columns.str.replace('latitude','contact_month')
df.columns=df.columns.str.replace('longitude','contact_year')

### Cambiar 'date' a tipo fecha

In [4]:
locale.setlocale(locale.LC_TIME, 'Spanish_Spain') 
df['date'] = pd.to_datetime(df['date'], format='%d-%B-%Y')
df.head(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,date,contact_month,contact_year,id_,income,kidhome,teenhome,dt_customer,numwebvisitsmonth
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-08-02,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2016-09-14,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2019-02-15,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2015-11-29,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2017-01-29,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20

Sustituimos los datos de latitud y longitud por los meses y años de la fecha date

In [5]:
df['contact_month']=df['date'].dt.month.astype('Int64')
df['contact_year']=df['date'].dt.year.astype('Int64')

Por consistencia la columna a los valores de la columna education, tambien le vamos a sustituir los . por _

In [6]:
df['education']=df['education'].str.replace('.','_')

In [7]:
df.sample(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,date,contact_month,contact_year,id_,income,kidhome,teenhome,dt_customer,numwebvisitsmonth
3736,37.0,services,MARRIED,high_school,0.0,0.0,0.0,telephone,680,3,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2018-11-24,11,2018,0d7f6f1e-d8a5-45fb-8f84-9ba5248d5f2f,139232,1,1,2012-10-20,32
8850,31.0,management,SINGLE,university_degree,NaN,0.0,1.0,telephone,690,2,999,0,NONEXISTENT,1.4,"94,465","-41,8","4,866","5228,1",no,2019-06-30,6,2019,15e211b9-8b21-4daf-a423-91c9ef9acca8,19568,0,0,2012-04-04,21
16725,NaN,technician,MARRIED,high_school,NaN,1.0,1.0,telephone,193,1,999,0,NONEXISTENT,1.4,"93,918","-42,7",NaN,"5228,1",no,2018-06-05,6,2018,236a2497-19ad-427f-986b-33f920beaf3f,154491,0,1,2012-08-01,26
22926,38.0,admin.,MARRIED,university_degree,0.0,1.0,0.0,cellular,427,12,999,0,NONEXISTENT,1.4,"93,444","-36,1",NaN,"5228,1",no,2015-12-09,12,2015,c07ab22b-d9bf-44d9-a540-914cb2a02253,52182,2,2,2013-01-03,12
11498,36.0,blue-collar,SINGLE,basic_9y,NaN,NaN,NaN,telephone,25,3,999,0,NONEXISTENT,1.4,"94,465","-41,8","4,959","5228,1",no,2019-03-04,3,2019,6f033546-2e95-40ac-a034-79533380936e,121612,0,0,2012-09-24,19

### Cambiar 'Age' a tipo int

In [8]:
df['age']=df['age'].astype('Int64')

### Cambiamos registros admin. por administrative en la columna job

In [9]:
df['job']=df['job'].replace({'admin.':'administrative'})

### Cambiar registros a minusculas

In [10]:
col_objetos=df.select_dtypes(include='object').columns
df[col_objetos]=df[col_objetos].apply(lambda col: col.str.lower())

### Cambio de datos de columnas object a boolean
Estudiamos valores de la columna 'default', 'housing', 'loan' y 'y'. Incialmente estos datos son de tipo object y representan un numero 0.0  1.0, yes o no. Decidimos cambiar todas ellas a tipo boolean de manera que true represente valores 1 o yes y false represente valores 0 o no.

In [11]:
col_bol=['default','housing', 'loan', 'y']

for col in col_bol:
  print (f"Distribución de valores en la columna '{col}':")
  print (df[col].value_counts())
  df[col] = df[col].replace({
    'yes': True, 'no': False,
    '1': True, '0': False,
    1: True, 0: False})
  df[col]=df[col].astype(bool)

Distribución de valores en la columna 'default':
default
0.0    34016
1.0        3
Name: count, dtype: int64
Distribución de valores en la columna 'housing':
housing
1.0    22498
0.0    19476
Name: count, dtype: int64
Distribución de valores en la columna 'loan':
loan
0.0    35442
1.0     6532
Name: count, dtype: int64
Distribución de valores en la columna 'y':
y
no     38156
yes     4844
Name: count, dtype: int64

C:\Users\inaki\AppData\Local\Temp\ipykernel_10144\300460610.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].replace({

### Cambio de columnas object de indices a float 
Cambiamos los datos que representan índices bursátiles y son tipo object a tipo float. Estos datos aparecen en las columnas 'cons_price_idx', 'cons_conf_idx', 'euribor3m'

In [12]:
col_index=['cons_price_idx', 'cons_conf_idx', 'euribor3m']
for col in col_index:
    df[col] = df[col].str.replace(',','.')
    df[col]=df[col].astype(float)
df.sample(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,date,contact_month,contact_year,id_,income,kidhome,teenhome,dt_customer,numwebvisitsmonth
33243,36,blue-collar,married,basic_9y,False,False,False,cellular,395,2,999,0,nonexistent,-1.8,92.893,-46.2,NaN,"5099,1",False,2018-05-06,5,2018,174b2820-bb83-427b-9c86-6f956ba6bd81,137958,0,0,2014-12-09,12
40724,29,technician,married,professional_course,False,True,False,cellular,319,1,5,2,success,-1.1,94.601,-49.5,0.972,"4963,6",True,2017-05-18,5,2017,24cb751e-b8f3-41c1-97ed-cd680ed56ca4,9849,2,2,2014-07-16,5
31234,29,administrative,single,university_degree,False,False,False,cellular,198,2,999,2,failure,-1.8,92.893,-46.2,1.334,"5099,1",False,2018-06-16,6,2018,5b6a56e5-b064-4525-ae61-fa9caa894c3c,140434,0,1,2014-03-18,2
30106,40,services,married,high_school,False,True,False,cellular,124,1,999,1,failure,-1.8,93.075,-47.1,1.365,"5099,1",False,2017-07-16,7,2017,be490b4d-6c1e-4040-9a31-e3d851d12990,114040,1,0,2014-09-22,3
40523,64,retired,divorced,basic_4y,False,True,True,telephone,211,2,6,2,success,-1.1,94.199,-37.5,0.878,"4963,6",True,2015-08-22,8,2015,c0c070ea-2f33-40eb-aee4-7dd65a288059,45224,1,2,2014-08-03,7